global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'events-producer'
    static_configs:
      - targets: ['localhost:8000', 'host.docker.internal:8000']

  - job_name: 'events-consumer'
    static_configs:
      - targets: ['localhost:8001', 'host.docker.internal:8001']