global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'events-producer'
    static_configs:
      - targets: ['events-producer:8000']

  - job_name: 'events-consumer'
    static_configs:
      - targets: ['events-consumer:8001']

  - job_name: 'kafka-exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
    scrape_interval: 10s
